version: '3'
services:
  web:
    image: nginx
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    volumes:
      # if this is /root:/usr/share/nginx/html
      # then the container won't have access to
      # read the contents of the folder.
      - /code:/usr/share/nginx/html
      - /code/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  app:
    image: php:fpm
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    volumes:
      - /code:/usr/share/nginx/html
    networks:
      - backend
  cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend
networks:
  backend:
